#!/bin/bash
#Environment initialization
initenv()
{
  system=`cat /etc/redhat-release  | awk '{print $(NF-1)}' | awk -F'.' '{print $1}'`
}
#Install basic packages
INSTALL_PACKAGES()
{
 # yum -y install gcc gcc-c++ openssl openssl-devel openssh-clients wget make lrzsz unzip zip xz lsof telnet epel-release vim tree kernel-devel kernel man
 yum -y install gcc gcc-c++ openssl openssl-devel openssh-clients wget make lrzsz unzip zip xz lsof telnet epel-release vim tree  man
}

#close selinux
CLOSE_SELINUX()
{
  setenforce 0
  sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
}

#Configure iptables
IPTABLES()
{
  if [ $system -eq 7 ];then
    #systemctl stop firewalld.service
    #systemctl disable firewalld.service

    yum -y install iptables-services
    cat > /etc/sysconfig/iptables << eof
# sample configuration for iptables service
# you can edit this manually or use system-config-firewall
# please do not ask us to add additional ports/services to this default configuration
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
eof
    systemctl start iptables.service
    systemctl enable iptables.service
  elif [ $system -eq 6 ];then
    cat > /etc/sysconfig/iptables << eof
# sample configuration for iptables service
# you can edit this manually or use system-config-firewall
# please do not ask us to add additional ports/services to this default configuration
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
eof
    /etc/init.d/iptables  start
    chkconfig iptables on
  fi
}
  
#ntp date
NTPDATE()
{
  yum -y install ntpdate
  
  if [ $system -eq 7 ];then
    systemctl enable ntpdate
    systemctl start ntpdate
  elif [ $system -eq 6 ];then
    chkconfig ntpdate on
    service ntpdate start
  fi  
}

#add /etc/rc.d/rc.local x perm
#centos7 default no x perm
ADD_X_PERM()
{
  chmod +x /etc/rc.d/rc.local
}

#set time zone
SET_TIME_ZONE()
{
  if [ $system -eq 7 ];then 
    timedatectl set-timezone Asia/Shanghai
  elif [ $system -eq 6 ];then
    rm -f /etc/localtime
    ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  fi
}

#set dns
SET_DNS()
{
  cat > /etc/resolv.conf << eof
# Generated by NetworkManager
search quark.com
nameserver 172.30.30.30
nameserver 172.30.30.31
eof
}

#optimize kernel
OPTIMIZE_KERNEL()
{
  num=`grep -vE '#' /etc/sysctl.conf | grep net.core.somaxconn |wc -l`
  if [ $num -eq 0 ];then
  cat >> /etc/sysctl.conf << eof
net.core.somaxconn = 4096
eof
  fi

  num=`grep -vE '#' /etc/sysctl.conf | grep net.ipv4.ip_local_port_range |wc -l`
  if [ $num -eq 0 ];then
  cat >> /etc/sysctl.conf << eof
net.ipv4.ip_local_port_range = 4096 65000
eof
  fi

  num=`grep -vE '#' /etc/sysctl.conf | grep net.core.netdev_max_backlog |wc -l`
  if [ $num -eq 0 ];then
  cat >> /etc/sysctl.conf << eof
net.core.netdev_max_backlog = 65000
eof
  fi

  num=`grep -vE '#' /etc/sysctl.conf | grep net.ipv4.tcp_max_syn_backlog |wc -l`
  if [ $num -eq 0 ];then
  cat >> /etc/sysctl.conf << eof
net.ipv4.tcp_max_syn_backlog = 8196
eof
  fi
  
  sysctl -p
}

#Modify nofile
NOFILE()
{
  find /etc/security/limits.d/ -type f -delete
  if [ $num -eq 0 ];then
  cat > /etc/security/limits.d/10-nproc.conf << eof
*    soft      nproc     10240
*    hard      nproc     10240
*    soft      nofile    65535
*    hard      nofile    65535
eof
  echo "==========================
please exit terminal,then open a new terminal
=========================="
  fi
}

install_addhost_zabbix()
{
system_version=`uname -r`
if [ $system -eq 6 ];then
	sudo yum install unixODBC  wget  -y 
	sudo rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-agent-3.0.0-2.el6.x86_64.rpm http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-get-3.0.0-2.el6.x86_64.rpm   http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-sender-3.0.0-2.el6.x86_64.rpm
	if [ $? -eq 0 ];then
		echo '################# 0 centos6 yum zabbixclient OK,continue please##########################'
	else
		echo '################# 0 centos6 yum zab cli error ##########################'
		exit 1
	fi
	sleep 60
	api_ins_zab_agent
elif [ $system -eq 7 ];then
    sudo yum install unixODBC  wget  -y 
	sudo rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-agent-3.0.8-2.el7.x86_64.rpm  http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-get-3.0.8-2.el7.x86_64.rpm  http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-sender-3.0.8-2.el7.x86_64.rpm  
	if [ $? -eq 0 ];then
		echo '################# 0 centos7 yum zabbixclient OK,continue please##########################'
	else
		echo '################# 0 centos7 yum zabbixclient error ##########################'
		exit 1
	fi
	sleep 60
	api_ins_zab_agent
else
    echo "the system is not centos6 or centos7,Please install manually zabbix-agent by yourself "
fi
}	
	
api_ins_zab_agent(){	
	sudo cp /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.default
	sudo sed -i 's/Server=.*/Server=172.30.32.89,172.16.250.50/g'  /etc/zabbix/zabbix_agentd.conf
	sudo sed -i 's/ServerActive=.*/ServerActive=172.30.32.89,172.16.250.50/g'  /etc/zabbix/zabbix_agentd.conf
	sudo sed -i 's/# Timeout=.*/Timeout=30/g' /etc/zabbix/zabbix_agentd.conf
	sudo sed -i 's/LogFileSize=.*/LogFileSize=50/g'  /etc/zabbix/zabbix_agentd.conf
	sudo sed -i "s/Hostname=.*/Hostname=$HOSTNAME/g"  /etc/zabbix/zabbix_agentd.conf
	sudo sed -i 's/# UnsafeUserParameters=.*/UnsafeUserParameters=1/g'   /etc/zabbix/zabbix_agentd.conf
	sudo sed -i 's%Include=/etc/zabbix/zabbix_agentd.d/%Include=/etc/zabbix/zabbix_agentd.d/*.conf%g'   /etc/zabbix/zabbix_agentd.conf
	sudo iptables -I INPUT -p tcp -m state --state NEW -m tcp --dport  80 -j ACCEPT
	sudo iptables -I INPUT -s 172.16.250.50/32 -p tcp -m tcp --dport 10050 -j ACCEPT
	sudo iptables -I INPUT -s 172.30.32.89/32 -p tcp -m tcp --dport 10050 -j ACCEPT
	#sudo iptables -I OUTPUT -d 172.16.250.50/32 -p tcp -m tcp --sport 10050 -j ACCEPT
	#sudo iptables -I OUTPUT -d 172.30.32.89/32 -p tcp -m tcp --sport 10050 -j ACCEPT
	sudo service iptables save
	sudo chkconfig zabbix-agent on
	sudo service zabbix-agent start
	SERVER=172.16.250.50
	if [ $system -eq 6 ];
	  then
	IP=`ifconfig eth0| grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
	  else 
	IP=`ifconfig | grep "inet "  | awk  '{print $2}' | sed -n '/172.*/p'`
	  fi
	API='http://172.16.250.50/zabbix/api_jsonrpc.php'
	ZABBIX_USER=ApiUser
	ZABBIX_PASS=Password@1
	AUTH_TOKEN=`wget -O- -o /dev/null $API --header 'Content-Type: application/json-rpc' --post-data "{\"jsonrpc\": \"2.0\",\"method\": \"user.login\",\"params\": {\"user\": \"$ZABBIX_USER\",\"password\": \"$ZABBIX_PASS\"},\"id\": 1}" | cut -d'"' -f8`
	echo $AUTH_TOKEN
	wget -O- -o /dev/null $API --header 'Content-Type: application/json-rpc' --post-data "{\"jsonrpc\": \"2.0\", \"method\": \"hostgroup.get\",\"params\": {\"output\": \"extend\", \"sortfield\": \"name\"},\"auth\": \"$AUTH_TOKEN\", \"id\": 1}"
	#wget -O- -o /dev/null $API --header 'Content-Type: application/json-rpc' --post-data "{\"jsonrpc\": \"2.0\", \"method\": \"template.get\",\"params\": {\"output\": \"extend\"},\"auth\": \"$AUTH_TOKEN\", \"id\": 1}"
	TEMPLATEID=10294
	GROUPID=10
	curl -i -X POST -H 'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\": \"host.create\",\"params\": { \"host\": \"$HOSTNAME\",\"interfaces\": [ {\"type\": 1,\"main\": 1,\"useip\": 1,\"ip\": \"$IP\",\"dns\": \"\",\"port\": \"10050\"}],\"groups\": [{\"groupid\": \"$GROUPID\"}],\"templates\": [ {\"templateid\": \"$TEMPLATEID\"}]},\"auth\": \"$AUTH_TOKEN\",\"id\": 1}" $API
	}
cen6LdapCliIns(){
	#sudo su -
	#centos6.6 install openldap client
	#0 remove sssd
	 yum remove sssd* -y
	 #1 install yum client pam lib
	yum -y install openldap-clients nss-pam-ldapd
	if [ $? -eq 0 ];then
		echo '################# 0 centos6 yum ldapclient OK,continue please##########################'
	else
		echo '################# 0 centos6 yum ldap error ##########################'
		exit 1
	fi
	#2 authconfig conf
	authconfig --enableldap --enableldapauth --ldapserver=ldaps://ldap1.quark.com,ldaps://ldap5-qf.quark.com,ldaps://ldap4.quark.com,ldaps://ldap2.quark.com,ldaps://ldap3.quark.com --ldapbasedn="dc=quark,dc=com" --enablemkhomedir  --enableldaptls --enableforcelegacy --disablesssd --disablesssdauth --enablelocauthorize --update
	#3 conf nslcd 
	echo 'tls_reqcert allow'>>/etc/nslcd.conf
	sed -i 's/start_tls/on/g' /etc/nslcd.conf
	echo 'filter passwd (gidNumber=3003)'>>/etc/nslcd.conf
	#4 conf pam_ldap.conf
	sed -i 's/start_tls/on/g' /etc/pam_ldap.conf
	echo 'tls_reqcert allow'>>/etc/pam_ldap.conf
	#5 conf /etc/openldap/ldap.conf
cat >/etc/openldap/ldap.conf <<EOF
TLS_CACERTDIR /etc/openldap/cacerts
URI ldaps://ldap1.quark.com,ldaps://ldap5-qf.quark.com,ldaps://ldap4.quark.com,ldaps://ldap2.quark.com,ldaps://ldap3.quark.com
BASE dc=quark,dc=com
SSL on
TLS_REQCERT allow
EOF
	#6 conf /etc/nsswithch.conf sudoers privillage
	echo 'sudoers:    files ldap'>>/etc/nsswitch.conf
	#7 /etc/sudo-ldap.conf config
cat >/etc/sudo-ldap.conf <<EOF
#uri ldap://ldaptest.com
uri ldaps://ldap1.quark.com,ldaps://ldap5-qf.quark.com,ldaps://ldap4.quark.com,ldaps://ldap2.quark.com,ldaps://ldap3.quark.com
base dc=quark,dc=com
tls_cacertdir /etc/openldap/cacerts
ssl on
tls_reqcert allow
sudoers_base ou=SUDOers,dc=quark,dc=com
EOF
	#8 check id is ok
	service nslcd restart
	id opa
	if [ $? -eq 0 ];then
	echo '#################8 centos6 config ldap_client OK,continue please##########################'
	else
	echo '################# 8 config centos6 ldap error ##########################'
	exit 1
	fi
}

cen7LdapCliIns(){
	#sudo su -
	#0 install yum client pam lib
	yum -y install openldap-clients nss-pam-ldapd
	if [ $? -eq 0 ];then
		echo '################# 0 centos7 yum ldapclient OK,continue please##########################'
	else
		echo '################# 0 centos7 yum ldap error ##########################'
		exit 1
	fi
	#1 authconfig config ldap
	authconfig --enableldap --enableldapauth --ldapserver=ldaps://ldap1.quark.com,ldaps://ldap5-qf.quark.com,ldaps://ldap4.quark.com,ldaps://ldap2.quark.com,ldaps://ldap3.quark.com --ldapbasedn="dc=quark,dc=com" --enablemkhomedir  --enableldaptls --enableforcelegacy --disablesssd --disablesssdauth --enablelocauthorize --update
	sed -i 's/start_tls/on/g' /etc/nslcd.conf
	echo 'tls_reqcert allow'>>/etc/nslcd.conf
	echo 'filter passwd (gidNumber=3003)'>>/etc/nslcd.conf
	service nslcd restart
	#2 enable sudo privillage
cat >/etc/sudo-ldap.conf <<EOF
uri ldaps://ldap1.quark.com,ldaps://ldap5-qf.quark.com,ldaps://ldap4.quark.com,ldaps://ldap2.quark.com,ldaps://ldap3.quark.com
sudoers_base ou=SUDOers,dc=quark,dc=com
base dc=quark,dc=com
tls_cacertdir /etc/openldap/cacerts
ssl on
tls_reqcert allow
EOF
	echo 'sudoers:    files ldap'>>/etc/nsswitch.conf
	#3 check id is ok
	echo 'tls_cacertdir /etc/openldap/cacerts' >>/etc/openldap/ldap.conf
	echo 'ssl on' >>/etc/openldap/ldap.conf
	echo 'tls_reqcert allow' >>/etc/openldap/ldap.conf

	service nslcd restart
	id opa
	if [ $? -eq 0 ];then
	echo '#################3 centos7 config ldap_client OK,continue please##########################'
	else
	echo '################# 3 config centos7 ldap error ##########################'
	exit 1
	fi
}
insLDAPClient(){
if [ $system -eq 6 ];then
	cen6LdapCliIns
elif [ $system -eq 7 ];then
	cen7LdapCliIns
else
	echo "################################## your system is not centos6 or centos7 ,please read the document or main web ################# "
	exit 1
fi
}

##删除系统默认 Java 版本
yum  remove -y  java

initenv
INSTALL_PACKAGES
CLOSE_SELINUX
IPTABLES
SET_TIME_ZONE
NTPDATE
ADD_X_PERM
SET_DNS
OPTIMIZE_KERNEL
NOFILE
install_addhost_zabbix
insLDAPClient
